apiVersion: v1
entries:
  nacos:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2022-11-25T11:15:36.5478912+08:00"
    description: A Helm chart nacos-k8s for Kubernetes
    digest: 687cc94f8db27e84c742e34e5f2bf9a87ecf21379120808c15bc3bcdee9ea351
    maintainers:
    - name: arrowfeng
    - name: paderlol
    name: nacos
    urls:
    - https://heretac.github.io/helm-charts/charts/nacos/nacos-0.1.5.tgz
    version: 0.1.5
generated: "2022-11-25T11:15:36.5468878+08:00"
